name: Build and Run Micronaut on JDK 17

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build with Maven
      run: mvn -DskipTests package

    - name: Run Application
      run: |
        nohup java -Dmicronaut.server.port=8086 -jar target/*-all.jar &
        sleep 10
        curl -I http://localhost:8086/swagger/task-api-v1.yml

